[project]
name = "simplecalculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "uvicorn>=0.32.1",
    "pytest>=8.3.3",
    "httpx>=0.27.2",
]
